# Image of workspace. Learn more: https://www.gitpod.io/docs/configure/workspaces/workspace-image
image:
  file: .gitpod/.gitpod.Dockerfile
tasks:
  - name: switch to ZSH
    command: |
      exec zsh
      bash -lic 'true'
vscode:
  extensions:
    - aaron-bond.better-comments
    - ahmadawais.emoji-log-vscode
    - albert.TabOut
    - aliariff.auto-add-brackets
    - AmazonWebServices.aws-toolkit-vscode
    - charliermarsh.ruff
    - christian-kohler.path-intellisense
    - chrmarti.regex
    - DavidAnson.vscode-markdownlint
    - dbaeumer.vscode-eslint
    - devAdvice.serverlessconsole
    - donjayamanne.githistory
    - EditorConfig.EditorConfig
    - eriklynd.json-tools
    - esbenp.prettier-vscode
    - formulahendry.auto-close-tag
    - formulahendry.auto-rename-tag
    - GitHub.copilot-chat
    - GitHub.copilot
    - github.vscode-github-actions
    - hbenl.vscode-test-explorer
    - howardzuo.vscode-git-tags
    - johnpapa.vscode-cloak
    - KevinRose.vsc-python-indent
    - LittleFoxTeam.vscode-python-test-adapter
    - meganrogge.template-string-converter
    - mikestead.dotenv
    - mrmlnc.vscode-duplicate
    - ms-python.black-formatter
    - ms-python.debugpy
    - ms-python.mypy-type-checker
    - ms-python.pylint
    - ms-python.python
    - ms-python.vscode-pylance
    - oderwat.indent-rainbow
    - oliversturm.fix-json
    - pnp.polacode
    - qcz.text-power-tools
    - redhat.vscode-yaml
    - shardulm94.trailing-spaces
    - shd101wyy.markdown-preview-enhanced
    - streetsidesoftware.code-spell-checker
    - tamasfe.even-better-toml
    - vincaslt.highlight-matching-tag
    - VisualStudioExptTeam.vscodeintellicode
    - waderyan.gitblame
    - wholroyd.jinja
    - almenon.arepl
    - donjayamanne.python-environment-manager
    - DotJoshJohnson.xml
    - LittleFoxTeam.vscode-python-test-adapter
    - ms-python.autopep8
    - ms-python.black-formatter
    - ms-python.flake8
    - njpwerner.autodocstring
    - njqdev.vscode-python-typehint
    - redhat.vscode-xml
    - VisualStudioExptTeam.vscodeintellicode
